use_frameworks!

platform :ios, '11.0'

target 'JMQuotesComponets_Example' do
  pod 'JMQuotesComponets', :path => '../'

  target 'JMQuotesComponets_Tests' do
    inherit! :search_paths

    
  end
end
